//>>built
!function(x){"object"==typeof module&&"object"==typeof module.exports?(x=x(),void 0!==x&&(module.exports=x)):"function"==typeof define&&define.amd&&define([],x)}(function(){function x(a,c,b){b=b||2;var f=c&&c.length,d=f?c[0]*b:a.length,h=J(a,0,d,b,!0),k=[];if(!h||h.next===h.prev)return k;var l;if(f){var g=b,n;var e=[];f=0;for(n=c.length;f<n;f++){var u=c[f]*g;var q=f<n-1?c[f+1]*g:a.length;u=J(a,u,q,g,!1);u===u.next&&(u.steiner=!0);e.push(O(u))}e.sort(P);for(f=0;f<e.length;f++){g=e[f];c=h;if(c=Q(g,
c))g=K(c,g),y(c,c.next),y(g,g.next);h=y(h,h.next)}}if(a.length>80*b){var r=l=a[0];var m=f=a[1];for(g=b;g<d;g+=b)e=a[g],c=a[g+1],e<r&&(r=e),c<m&&(m=c),e>l&&(l=e),c>f&&(f=c);l=Math.max(l-r,f-m);l=0!==l?1/l:0}return A(h,k,b,r,m,l),k}function J(a,c,b,f,d){if(d===0<G(a,c,b,f))for(d=c;d<b;d+=f)var h=L(d,a[d],a[d+1],h);else for(d=b-f;d>=c;d-=f)h=L(d,a[d],a[d+1],h);return h&&D(h,h.next)&&(B(h),h=h.next),h}function y(a,c){if(!a)return a;c||(c=a);var b=a;do if(a=!1,b.steiner||!D(b,b.next)&&0!==v(b.prev,b,b.next))b=
b.next;else{if(B(b),b=c=b.prev,b===b.next)break;a=!0}while(a||b!==c);return c}function A(a,c,b,f,d,h,k){if(a){!k&&h&&M(a,f,d,h);for(var l,g,n=a;a.prev!==a.next;){l=a.prev;g=a.next;if(h)a:{var e=a;var u=f,q=d,r=h,m=e.prev,t=e,p=e.next;if(0<=v(m,t,p))e=!1;else{var R=m.x>t.x?m.x>p.x?m.x:p.x:t.x>p.x?t.x:p.x,S=m.y>t.y?m.y>p.y?m.y:p.y:t.y>p.y?t.y:p.y,w=H(m.x<t.x?m.x<p.x?m.x:p.x:t.x<p.x?t.x:p.x,m.y<t.y?m.y<p.y?m.y:p.y:t.y<p.y?t.y:p.y,u,q,r);u=H(R,S,u,q,r);q=e.prevZ;for(r=e.nextZ;q&&q.z>=w&&r&&r.z<=u;){if(q!==
e.prev&&q!==e.next&&z(m.x,m.y,t.x,t.y,p.x,p.y,q.x,q.y)&&0<=v(q.prev,q,q.next)||(q=q.prevZ,r!==e.prev&&r!==e.next&&z(m.x,m.y,t.x,t.y,p.x,p.y,r.x,r.y)&&0<=v(r.prev,r,r.next))){e=!1;break a}r=r.nextZ}for(;q&&q.z>=w;){if(q!==e.prev&&q!==e.next&&z(m.x,m.y,t.x,t.y,p.x,p.y,q.x,q.y)&&0<=v(q.prev,q,q.next)){e=!1;break a}q=q.prevZ}for(;r&&r.z<=u;){if(r!==e.prev&&r!==e.next&&z(m.x,m.y,t.x,t.y,p.x,p.y,r.x,r.y)&&0<=v(r.prev,r,r.next)){e=!1;break a}r=r.nextZ}e=!0}}else a:if(e=a,m=e.prev,t=e,p=e.next,0<=v(m,t,p))e=
!1;else{for(w=e.next.next;w!==e.prev;){if(z(m.x,m.y,t.x,t.y,p.x,p.y,w.x,w.y)&&0<=v(w.prev,w,w.next)){e=!1;break a}w=w.next}e=!0}if(e)c.push(l.i/b),c.push(a.i/b),c.push(g.i/b),B(a),n=a=g.next;else if(a=g,a===n){if(k)if(1===k){a=y(a);k=c;l=b;g=a;do n=g.prev,e=g.next.next,!D(n,e)&&N(n,g,g.next,e)&&C(n,e)&&C(e,n)&&(k.push(n.i/l),k.push(g.i/l),k.push(e.i/l),B(g),B(g.next),g=a=e),g=g.next;while(g!==a);a=y(g);A(a,c,b,f,d,h,2)}else{if(2===k)a:{k=a;do{for(l=k.next.next;l!==k.prev;){if(g=k.i!==l.i){e=e=e=e=
void 0;g=k;n=l;if(e=g.next.i!==n.i&&g.prev.i!==n.i){b:{e=g;do{if(e.i!==g.i&&e.next.i!==g.i&&e.i!==n.i&&e.next.i!==n.i&&N(e,e.next,g,n)){e=!0;break b}e=e.next}while(e!==g);e=!1}e=!e}if(e){if(e=C(g,n)&&C(n,g)){e=g;m=!1;t=(g.x+n.x)/2;p=(g.y+n.y)/2;do e.y>p!=e.next.y>p&&e.next.y!==e.y&&t<(e.next.x-e.x)*(p-e.y)/(e.next.y-e.y)+e.x&&(m=!m),e=e.next;while(e!==g);e=m}e=e&&(v(g.prev,g,n.prev)||v(g,n.prev,n))||D(g,n)&&0<v(g.prev,g,g.next)&&0<v(n.prev,n,n.next)}g=e}if(g){a=K(k,l);k=y(k,k.next);a=y(a,a.next);
A(k,c,b,f,d,h);A(a,c,b,f,d,h);break a}l=l.next}k=k.next}while(k!==a)}}else A(y(a),c,b,f,d,h,1);break}}}}function P(a,c){return a.x-c.x}function Q(a,c){var b=c,f=a.x,d=a.y,h=-(1/0);do{if(d<=b.y&&d>=b.next.y&&b.next.y!==b.y){var k=b.x+(d-b.y)*(b.next.x-b.x)/(b.next.y-b.y);if(k<=f&&k>h){if(h=k,k===f){if(d===b.y)return b;if(d===b.next.y)return b.next}var l=b.x<b.next.x?b:b.next}}b=b.next}while(b!==c);if(!l)return null;if(f===h)return l;k=l;var g=l.x,n=l.y,e=1/0;b=l;do{if(f>=b.x&&b.x>=g&&f!==b.x&&z(d<
n?f:h,d,g,n,d<n?h:f,d,b.x,b.y)){c=Math.abs(d-b.y)/(f-b.x);var u;if((u=C(b,a))&&!(u=c<e)&&(u=c===e)&&!(u=b.x>l.x)&&(u=b.x===l.x)){u=l;var q=b;u=0>v(u.prev,u,q.prev)&&0>v(q.next,u,u.next)}u&&(l=b,e=c)}b=b.next}while(b!==k);return l}function M(a,c,b,f){var d=a;do{if(null===d.z&&(d.z=H(d.x,d.y,c,b,f)),d.prev.next!==d||d.next.prev!==d)return d.prev.next=d,d.next.prev=d,M(a,c,b,f);d.prevZ=d.prev;d=d.nextZ=d.next}while(d!==a);d.prevZ.nextZ=null;d.prevZ=null;a=d;var h,k,l,g=1;do{c=a;f=a=null;for(d=0;c;){d++;
b=c;for(h=l=0;h<g&&(l++,b=b.nextZ,b);h++);for(h=g;0<l||0<h&&b;)0!==l&&(0===h||!b||c.z<=b.z)?(k=c,c=c.nextZ,l--):(k=b,b=b.nextZ,h--),f?f.nextZ=k:a=k,k.prevZ=f,f=k;c=b}f.nextZ=null;g*=2}while(1<d)}function H(a,c,b,f,d){return a=32767*(a-b)*d,c=32767*(c-f)*d,a=16711935&(a|a<<8),a=252645135&(a|a<<4),a=858993459&(a|a<<2),a=1431655765&(a|a<<1),c=16711935&(c|c<<8),c=252645135&(c|c<<4),c=858993459&(c|c<<2),c=1431655765&(c|c<<1),a|c<<1}function O(a){var c=a,b=a;do(c.x<b.x||c.x===b.x&&c.y<b.y)&&(b=c),c=c.next;
while(c!==a);return b}function z(a,c,b,f,d,h,k,l){return 0<=(d-k)*(c-l)-(a-k)*(h-l)&&0<=(a-k)*(f-l)-(b-k)*(c-l)&&0<=(b-k)*(h-l)-(d-k)*(f-l)}function v(a,c,b){return(c.y-a.y)*(b.x-c.x)-(c.x-a.x)*(b.y-c.y)}function D(a,c){return a.x===c.x&&a.y===c.y}function N(a,c,b,f){var d=E(v(a,c,b)),h=E(v(a,c,f)),k=E(v(b,f,a)),l=E(v(b,f,c));return d!==h&&k!==l||!(0!==d||!F(a,b,c))||!(0!==h||!F(a,f,c))||!(0!==k||!F(b,a,f))||!(0!==l||!F(b,c,f))}function F(a,c,b){return c.x<=Math.max(a.x,b.x)&&c.x>=Math.min(a.x,b.x)&&
c.y<=Math.max(a.y,b.y)&&c.y>=Math.min(a.y,b.y)}function E(a){return 0<a?1:0>a?-1:0}function C(a,c){return 0>v(a.prev,a,a.next)?0<=v(a,c,a.next)&&0<=v(a,a.prev,c):0>v(a,c,a.prev)||0>v(a,a.next,c)}function K(a,c){var b=new I(a.i,a.x,a.y),f=new I(c.i,c.x,c.y),d=a.next,h=c.prev;return a.next=c,c.prev=a,b.next=d,d.prev=b,f.next=b,b.prev=f,h.next=f,f.prev=h,f}function L(a,c,b,f){a=new I(a,c,b);return f?(a.next=f.next,a.prev=f,f.next.prev=a,f.next=a):(a.prev=a,a.next=a),a}function B(a){a.next.prev=a.prev;
a.prev.next=a.next;a.prevZ&&(a.prevZ.nextZ=a.nextZ);a.nextZ&&(a.nextZ.prevZ=a.prevZ)}function I(a,c,b){this.i=a;this.x=c;this.y=b;this.nextZ=this.prevZ=this.z=this.next=this.prev=null;this.steiner=!1}function G(a,c,b,f){for(var d=0,h=b-f;c<b;c+=f)d+=(a[h]-a[c])*(a[c+1]+a[h+1]),h=c;return d}return x.deviation=function(a,c,b,f){var d=c&&c.length,h=Math.abs(G(a,0,d?c[0]*b:a.length,b));if(d){d=0;for(var k=c.length;d<k;d++)h-=Math.abs(G(a,c[d]*b,d<k-1?c[d+1]*b:a.length,b))}for(d=c=0;d<f.length;d+=3){k=
f[d]*b;var l=f[d+1]*b,g=f[d+2]*b;c+=Math.abs((a[k]-a[g])*(a[l+1]-a[k+1])-(a[k]-a[l])*(a[g+1]-a[k+1]))}return 0===h&&0===c?0:Math.abs((c-h)/h)},x.flatten=function(a){for(var c=a[0][0].length,b={vertices:[],holes:[],dimensions:c},f=0,d=0;d<a.length;d++){for(var h=0;h<a[d].length;h++)for(var k=0;k<c;k++)b.vertices.push(a[d][h][k]);0<d&&(f+=a[d-1].length,b.holes.push(f))}return b},x});