// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/aspect jimu/BaseWidgetPanel jimu/BaseWidgetFrame jimu/utils ./FoldableDijit ./FoldableWidgetFrame".split(" "),function(k,f,b,g,h,l,m,n,p,q,r){return k([m,q],{baseClass:"jimu-panel jimu-foldable-dijit jimu-foldable-panel",closeTolerance:30,openAnimation:"fadeIn",closeAnimation:"fadeOut",animationDuration:500,startup:function(){this.titleHeight=35;this.inherited(arguments);b.addClass(this.titleNode,"jimu-panel-title jimu-main-background");
this.createCloseBtn();this.createMaxBtn();this.createFoldableBtn();this.panelManager.normalizePanel(this)},getPanelPosition:function(){if(window.appInfo.isRunInMobile)return this.panelManager.getPositionOnMobile(this);var a=f.clone(this.position);"undefined"===typeof a.width&&(a.width=360);"minimized"===this.windowState?(a.bottom="auto",a.height=this.titleHeight,a.borderRadiusStyle={borderTopLeftRadius:"4px",borderTopRightRadius:"4px",borderBottomLeftRadius:0,borderBottomRightRadius:0}):(a.bottom=
this.position.bottom,a.height="auto",a.borderRadiusStyle={borderTopLeftRadius:"4px",borderTopRightRadius:"4px",borderBottomLeftRadius:"4px",borderBottomRightRadius:"4px"});return a},onNormalize:function(){this.resize()},onMaximize:function(){this.resize()},onMinimize:function(){this.resize()},resize:function(){this._switchMaxBtn();this._switchParentNode();var a=this.getPanelPosition();this.position.zIndex&&(a.zIndex=this.position.zIndex);var c=p.getPositionStyle(a);f.mixin(c,a.borderRadiusStyle);
b.setStyle(this.domNode,c);1<this.getChildren().length&&this._setFrameSize(a.contentHeight);this.inherited(arguments)},reloadWidget:function(a){this.inherited(arguments);this.isWidgetInPanel(a)&&(Array.isArray(this.config.widgets)||this.setTitleLabel(a.label))},updateConfig:function(a){this.inherited(arguments);this.setTitleLabel(a.label)},_switchMaxBtn:function(){window.appInfo.isRunInMobile?b.setStyle(this.maxNode,"display",""):b.setStyle(this.maxNode,"display","none")},_switchParentNode:function(){window.appInfo.isRunInMobile?
b.place(this.domNode,jimuConfig.layoutId):b.place(this.domNode,this.sceneView.map.id)},_setFrameSize:function(a){var c=0;g.forEach(this.getChildren(),function(d){d.folded||c++},this);"undefined"===typeof a&&(a=b.getContentBox(this.containerNode).h);var e=(a-(this.getChildren().length-c)*this.getChildren()[0].titleHeight)/c;g.forEach(this.getChildren(),function(d){d.folded?b.setStyle(d.domNode,{height:d.titleHeight+"px"}):b.setStyle(d.domNode,{height:e+"px"});d.resize()},this)},createCloseBtn:function(){this.closeNode=
b.create("div",{"class":"close-btn jimu-float-trailing"},this.titleNode);this.own(h(this.closeNode,"click",f.hitch(this,function(a){a.stopPropagation();this.panelManager.closePanel(this)})))},createMaxBtn:function(){this.maxNode=b.create("div",{"class":"max-btn jimu-float-trailing"},this.titleNode);this.own(h(this.maxNode,"click",f.hitch(this,function(a){a.stopPropagation();this.onMaxNodeClick()})))},createFrame:function(a){this.config.widgets&&1===this.config.widgets.length||!this.config.widgets?
a=new n:(a=new r({label:a.label,widgetManager:this.widgetManager}),l.after(a,"onFoldStateChanged",f.hitch(this,function(){var c=0;this._setFrameSize();g.forEach(this.getChildren(),function(e){e.folded||c++},this);g.forEach(this.getChildren(),function(e){e.foldEnable=e.folded||1!==c?!0:!1},this)})));return a},onFoldableNodeClick:function(){this.inherited(arguments);"minimized"===this.windowState?this.panelManager.normalizePanel(this):this.panelManager.minimizePanel(this)},onMaxNodeClick:function(){"maximized"===
this.windowState?this.panelManager.normalizePanel(this):this.panelManager.maximizePanel(this)},moveTitle:function(){this.isFull?this.folded?b.setStyle(this.domNode,{top:b.getMarginBox(jimuConfig.layoutId).h-this.titleHeight+"px"}):b.setStyle(this.domNode,{top:"0px"}):b.setStyle(this.domNode,{top:this.position.top+"px"})}})});